.circleci/config.yml

Draft PR setting up circle CI testing & docker push to quay
Whats not ideal: Container build is basically done twice. Circle creates separate container build environments for each `setup_remote_docker` for each build step. 
Possible solutions could be:
- Test and push in the same step. IMO its important that container tags should follow the scheme used by architect
- Don't test with `docker run`. Utilize the docker executor with their [python images](https://circleci.com/docs/2.0/circleci-images/#python)

add circle-ci config

---

Dockerfile

This PR updates the versions of helm, kubectl and ct in the container image.
I think the most important one is helm. I've seen an error like this: `Error: looks like "https://kubernetes-charts.storage.googleapis.com/" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden` in multiple repositories.

Update binaries in container

---

app_build_suite/build_steps/helm.py

Follow up to #28 seems its required to update the actual url instead of just the binary version to resolve calling the depreacted repo url.

Change stable helm repo url

---

Pipfile
Pipfile.lock
app_build_suite/build_steps/pytest.py
examples/apps/hello-world-app/tests/abs/Pipfile
examples/apps/hello-world-app/tests/abs/Pipfile.lock
examples/apps/hello-world-app/tests/abs/test_example.py

Update pytest-helm-chart so it uses the correct set of command line optioins.

update pytest-helm-charts and examples

---

.circleci/config.yml

It seems CI was not executed for tag 0.1.1..
IDK exactly if this will fix this.
My suggestion would be to wait for https://github.com/giantswarm/github/pull/95 because it'll enable the release automation for this repository.

enable all jobs for tags

---

Dockerfile

Towards https://github.com/giantswarm/giantswarm/issues/14666
Includes app-operator v3.0.0 and configures a shorter resync period and TTL for the finalizer cache. This means the TTL that was causing the problem is reduced from 15 mins to 1 min.

Update apptestctl to v0.6.0 to fix problem with re-running tests

---

Dockerfile
app_build_suite/build_steps/base_test_runner.py

Towards https://github.com/giantswarm/apptestctl/issues/77
When run against a fresh kind cluster uploading the tarball now succeeds. Fix was to wait for a ready chartmuseum pod.
```
{"caller":"github.com/giantswarm/apptestctl/cmd/bootstrap/runner.go:644","level":"debug","message":"waited for ready `chartmuseum-chartmuseum` deployment","time":"2021-01-11T15:05:05.975651+00:00"}
2021-01-11 15:05:05,988 app_build_suite.build_steps.base_test_runner INFO: App platform components bootstrapped and ready to use.
2021-01-11 15:05:06,049 app_build_suite.build_steps.repositories INFO: Uploading file '/abs/workdir/build/hello-world-app-0.1.2-9b57f4f882cb89760d8a7f7cd8c9d4c5272adb2d.tgz' to chart-museum.
2021-01-11 15:05:06,073 app_build_suite.build_steps.base_test_runner INFO: Creating App CR for app …
```

Use apptestctl v0.6.1 with chartmuseum wait fix

---

CHANGELOG.md
Dockerfile
README.md
app_build_suite/__main__.py
app_build_suite/build_steps/base_test_runner.py
app_build_suite/build_steps/build_step.py
app_build_suite/build_steps/cluster_manager.py
app_build_suite/build_steps/helm.py
app_build_suite/build_steps/pytest.py
app_build_suite/build_steps/test_stage_helpers.py
app_build_suite/cluster_providers/__init__.py
app_build_suite/cluster_providers/cluster_provider.py
app_build_suite/cluster_providers/external_cluster_provider.py
app_build_suite/cluster_providers/kind_cluster_provider.py
app_build_suite/utils/config.py
app_build_suite/utils/files.py
container-entrypoint.sh
dabs.sh
examples/apps/hello-world-app/Chart.yaml

This PR:
- adds support for creating `kind` clusters internally, for more complex CI/CD scenarios
- fixes some issues around how ClusterManager works
- fixes some bugs around checking keys in `context`
- fixes a bug when `--chart-dir` was used instead of short option `-c`

Kind support

---

Makefile.abs.mk
docs/CONTRIBUTING.md

This PR strips away the leadig `v` from the given tag when executing `make release TAG=vX.Y.Z`.
I've checked several repositories in the giantswarm organization and it seems git tags always have a leading `v` but container image tags do not. So this is the most sane way to fix this issue.

Fix container tag in dabs sh

---

CHANGELOG.md
Dockerfile
README.md
app_build_suite/__main__.py
app_build_suite/build_steps/build_step.py
app_build_suite/build_steps/helm.py
container-entrypoint.sh

- fix loading config file from the work dir root
- rename 'step_unit' to `step_validation` as the name was misleading
Note: it's possible to use `chart-dir` option from a config file if the file is in working dir's root

Multiple fixes

---

CHANGELOG.md
examples/apps/hello-world-app/Chart.yaml
resources/ct_schemas/gs_metadata_chart_schema.yaml
testrunner.Dockerfile
tests/build_steps/res_test_helm/Chart.yaml
tests/build_steps/res_test_helm/main.yaml
tests/e2e/test_example_app.py
tests/utils/test_files.py

This PR:
- adds 'compatibleProviders' list of string to `ct`'s schema validation file
- introduces e2e test, where the `app_build_suite` module is invoked to build the example app
Fixes: https://github.com/giantswarm/giantswarm/issues/15809

Add 'compatibleProviders' to schema

---

CHANGELOG.md
Dockerfile
app_build_suite/build_steps/base_test_runner.py
app_build_suite/build_steps/helm.py

- update binary dependencies:
- helm: 3.5.2
- chart-test: 3.3.1
- apptestctl: 0.7.0
- docker: 20.10.3
Closes: https://github.com/giantswarm/giantswarm/issues/15925

upgrade binary dependencies

---

CHANGELOG.md
app_build_suite/build_steps/helm.py

This PR adds handling of `requirements.lock` files for helm charts using `apiVersion: v1` and a `requirements.yaml` file.
Tested this while preparing giantswarm/cert-manager-app#139

Handle requirements.lock file when updating dependencies for helm lint

---

CHANGELOG.md
Dockerfile
resources/ct_schemas/gs_metadata_chart_schema.yaml

Update our derived chart-testing schema ahead of an actual chart-testing
release. Upstream PR: https://github.com/helm/chart-testing/pull/300

Update chart-testing schema to not require repository field in chart dependencies

---

dabs.sh

These are not required since `app-test-suite` exists.

Remove host network and docker socket mount from dabs script

---

Dockerfile

We're using a nine month old python version. Time to update (at least we should try)

Update python to 3.8.12

---

.circleci/config.yml
Dockerfile
Makefile.abs.mk

This PR contains the following changes:
- Use the python image used in the final container build stage to avoid having to pull alpine only for binary download
- Not much improval in regard of time, but dowloads less data
- Use the `docker` executor instead of `machine` for executing tests in CI
- Tests run for about 1 minute instead of 4:30
I think these changes will improve the time it takes to execute all CI steps

Refactor Dockerfile + CI config

---

.github/workflows/push-to-app-catalog.yaml
CHANGELOG.md

Towards https://github.com/giantswarm/giantswarm/issues/19941
This adds a reusable github action for building apps using ABS and pushing to a github repo.
I've been testing it with a test [catalog]( https://github.com/rossf7/example-catalog) and a fork of our [hello-world-app](https://github.com/rossf7/hello-world-app/blob/master/.github/workflows/push-to-app-catalog.yaml) and here is an example [run](https://github.com/rossf7/hello-world-app/runs/4940497070?check_suite_focus=true)
```yaml
name: 'Push to App Catalog'
on:
push:
tags:
- 'v*'
jobs:
push_to_app_catalog:
uses: giantswarm/app-build-suite/.github/workflows/push-to-app-catalog.yaml@github-action
with:
app_catalog: example-catalog
chart: hello-world-app
organization: rossf7
secrets:
envPAT: ${{ secrets.PAT }}
```

Add push-to-app-catalog github action

---

CHANGELOG.md
Dockerfile
app_build_suite/build_steps/helm.py
examples/apps/hello-world-app/.kube-linter.yaml

Kube-linter updated to 0.2.5. All-in validation disabled in the example app.

Update kube linter

---

CHANGELOG.md
app_build_suite/build_steps/giant_swarm_validators/helm.py
docs/helm-build-pipeline.md
tests/build_steps/giant_swarm_validators/test_helm_validators.py

Tested [here](https://regex101.com/r/TQDrjZ/1) but it is my first time with Python and regex :D 
We are in dire need of this because we use subcharts a lot and if the annotation is not set on the subchart, the value is empty
@piontec can you take a look pretty please?

Add chart dependency support to the team label

---

app_build_suite/__main__.py

Goal: reduce noise, make output easier to read.
FYI: I have no idea whether the change is all it takes. This is untested.
<details>
<summary>Before</summary>
```nohighlight
2022-12-01 13:58:25,458 step_exec_lib.steps INFO: Running pre-run step for HelmBuilderValidator
2022-12-01 13:58:25,458 step_exec_lib.steps INFO: Running pre-run step for GiantSwarmHelmValidator
2022-12-01 13:58:25,460 app_build_suite.build_steps.helm INFO: Running Giant Swarm validator 'C0001: HasTeamLabel'.
2022-12-01 13:58:25,462 app_build_suite.build_steps.helm INFO: Running Giant Swarm validator 'F0001: HasValuesSchema'.
2022-12-01 13:58:25,462 step_exec_lib.steps INFO: Running pre-run step for HelmGitVersionSetter
2022-12-01 13:58:25,463 step_exec_lib.steps INFO: Running pre-run step for HelmRequirementsUpdater …
```

Remove timestamp, module name, and level from log template

---

CHANGELOG.md
Dockerfile
Makefile.abs.mk
Pipfile
Pipfile.lock
app_build_suite/build_steps/giant_swarm_validators/icon.py
app_build_suite/build_steps/helm.py
dabs.sh
examples/apps/hello-world-app/Chart.yaml
examples/apps/hello-world-app/values.yaml
examples/tutorial/values.yaml
testrunner.Dockerfile

Updates dependencies:
- step-exec-lib - to fix the discovery of the most recent tag
- python to 3.12 and libs

Fix tag detection

---

.circleci/config.yml

Towards https://github.com/giantswarm/giantswarm/issues/31824
This PR should exclude commits to the default branch from triggering the "push-to-registries" and "push-to-app-catalog" workflows. The assumption is that these workflows should be triggered only by pushes to non-default branches and by release tags.
The reason we are making this PR is that we have encountered problems with container image replication that are likely caused by fast pushes of the same image tag with different content. In addition, this will help us avoid obsolete CI runs.
As a code owner, please review and merge this PR if possible.
If you have reasons to keep these workflows running for the default branch, please let us (Honeybadger) know. Thank you!

Exclude default branch in some CircleCI workflows
