giantswarm/app-build-suite

- .circleci/config.yml
- .coveragerc
- .flake8
- .gitignore
- .pre-commit-config.yaml
- Dockerfile
- Makefile
- Pipfile
- Pipfile.lock
- app_build_suite/__main__.py
- app_build_suite/build_steps/__init__.py
- app_build_suite/build_steps/build_step.py
- app_build_suite/build_steps/errors.py
- app_build_suite/build_steps/helm.py
- app_build_suite/components.py
- app_build_suite/utils/git.py
- dabs.sh
- pyproject.toml
- run-abs-in-docker.sh
- run-tests-in-docker.sh
- testrunner.Dockerfile
- tests/build_steps/dummy_build_step.py
- tests/build_steps/test_build_step.py
- tests/test_components.py
Another milestone PR to set main things in place. Next ones should finally be smaller.
This one includes:
- full test coverage of core basic classes
- support for `--skip-steps` option
- dabs.sh script should not break file permissions anymore
- bug fixes
> Add unit tests, improve a dozen other things

- Dockerfile
- Pipfile
- Pipfile.lock
- README.md
- app_build_suite/__main__.py
- app_build_suite/build_steps/build_step.py
- app_build_suite/build_steps/helm.py
- app_build_suite/components.py
- app_build_suite/utils/files.py
- examples/apps/.gitignore
- examples/apps/hello-world-app/Chart.yaml
- examples/apps/hello-world-app/templates/deployment.yaml
- examples/apps/hello-world-app/templates/psp.yaml
- examples/apps/hello-world-app/templates/rbac.yaml
- examples/apps/hello-world-app/templates/service-account.yaml
- examples/apps/hello-world-app/templates/service.yaml
- examples/apps/hello-world-app/values.schema.json
- examples/apps/hello-world-app/values.yaml
- pyproject.toml
- resources/ct_schemas/gs_metadata_chart_schema.yaml
- testrunner.Dockerfile
- tests/build_steps/dummy_build_step.py
- tests/build_steps/res_test_helm/Chart.yaml
- tests/build_steps/res_test_helm/main.yaml
- tests/build_steps/test_helm.py
- tests/utils/test_files.py
This PR:
- adds metadata generation according to our specs (https://intranet.giantswarm.io/docs/architecture-specs-adrs/specs/managed-apps/2020-05-05-app-versions-representation/#metadata-file-format)
- fixes minor issues
A lot of the changes are only about the included sample app chart in `examples/`.
> Metadata generation

- CHANGELOG.md
- app_build_suite/build_steps/helm.py
- tests/build_steps/res_test_helm/main.yaml
After the talk with Ross, we decided to keep more data in the metadata file.
> added new fields to the metadata file

- README.md
- app_build_suite/build_steps/base_test_runner.py
- app_build_suite/build_steps/build_step.py
- app_build_suite/build_steps/pytest.py
- docs/CONTRIBUTING.md
This includes:
- some basic docs to get started
- a fix for not working `--skip-tests` option
> Docs and fixes

- app_build_suite/build_steps/base_test_runner.py
The check was missing and now it's important to check for `apptestctl` version.
> add checking for apptestctl version

- README.md
- app_build_suite/build_steps/base_test_runner.py
- app_build_suite/build_steps/build_step.py
- app_build_suite/build_steps/pytest.py
- examples/apps/hello-world-app/Chart.yaml
- examples/apps/hello-world-app/templates/deployment.yaml
- examples/apps/hello-world-app/tests/abs/.gitignore
- examples/apps/hello-world-app/tests/abs/test_example.py
This PR:
- adds new class of tests - `smoke`
- makes the included example much more useful and real-life
- adds some docs to explain pipelines and steps.
Additionally, this shows how to add a new type of tests to abs.
> Add smoke test type

- .circleci/config.yml
Make circleci publish artifact on github
> Create dabs.sh release

- CHANGELOG.md
- app_build_suite/build_steps/helm.py
I ran into this when I executed app-build-suite with 
```
replace-chart-version-with-git: false
replace-app-version-with-git: false
generate-metadata: true
```
> Fix run without version replacement

- .editorconfig
- .envrc
- .gitignore
- .pre-commit-config.yaml
Useful tools to ensure consitency and easier development
> Support the use of editorconfig and direnv

- CHANGELOG.md
- app_build_suite/build_steps/base_test_runner.py
- app_build_suite/build_steps/helm.py
This PR contains fixes for the app cr creation.
> Fix app creation

- app_build_suite/build_steps/base_test_runner.py
- fixed crash when a configmap used for test-time values.yaml was used
- imrpoved logging
> fix bug in deleting cm; improve logging

- CHANGELOG.md
- Makefile.abs.mk
- app_build_suite/build_steps/helm.py
- tests/build_steps/res_test_helm/main.yaml
- tests/build_steps/test_helm.py
To fix: https://github.com/giantswarm/giantswarm/issues/15432
> Fix timestamp format in meta

- CHANGELOG.md
- app_build_suite/build_steps/helm.py
- tests/build_steps/res_test_helm/main.yaml
Closes https://github.com/giantswarm/giantswarm/issues/15431
> Add home and icon from Chart.yaml to main.yaml in metadata

- CHANGELOG.md
- app_build_suite/build_steps/helm.py
Fixes: https://github.com/giantswarm/giantswarm/issues/15872
Remove the autogenerated command line option. More info in Changelog.
> remove the --ct-chart-repos option

- README.md
- docs/helm3-build-pipeline.md
- cleanup, update and order docs
> Better docs

- README.md
- container-entrypoint.sh
- docs/CONTRIBUTING.md
- docs/pytest-test-pipeline.md
Tiny docs improvements and `versions` reporting.
> Pre release improvements

- .pre-commit-config.yaml
- README.md
- app_build_suite/build_steps/cluster_manager.py
- docs/tutorial.md
- examples/tutorial/.helmignore
- examples/tutorial/.kube-linter.yaml
- examples/tutorial/Chart.yaml
- examples/tutorial/templates/deployment.yaml
- examples/tutorial/templates/psp.yaml
- examples/tutorial/templates/rbac.yaml
- examples/tutorial/templates/service-account.yaml
- examples/tutorial/templates/service.yaml
- examples/tutorial/values.schema.json
- examples/tutorial/values.yaml
OK, part of "not really having idea for hackathon". I hope this makes getting started with abs much easier.
@MarcelMue as you kind of motivate me to write it down, please read it and provide feedback.
> add full tutorial

- Dockerfile
Fixes https://github.com/giantswarm/app-build-suite/issues/134
Needs testing.
> Update helm to 3.7.0

- Pipfile
- Pipfile.lock
Let's try to make renovate happy
> update dependecy spec

- README.md
Towards https://github.com/giantswarm/giantswarm/issues/14747
> Link to GitHub Action docs

- Makefile.abs.mk
- docs/CONTRIBUTING.md
I just released v1.1.0 with the github action.
However I'm using mac sed 😬 and needed to make this change. Should we revert it or try to make it support linux and macos?
> Remove makefile change needed for macos sed

- .circleci/config.yml
- .github/workflows/push-to-app-catalog.yaml
- .pre-commit-config.yaml
- CHANGELOG.md
- Dockerfile
- Pipfile
- Pipfile.lock
- app_build_suite/build_steps/helm.py
This PR updates the dependencies to newer versions
> Bump python

- Dockerfile
- renovate.json
Quality of life: try to configure renovate to automatically upgrade binaries in Dockerfile
> try: configure renovate for helm updates

- docs/helm-build-pipeline.md
Add a note so people don't have to look it up in `ct`'s docs every time.
> add info about configuring ct

- CHANGELOG.md
- examples/apps/hello-world-app/templates/_helpers.yaml
The feature has beenn added a while ago by @QuentinBisson (https://github.com/giantswarm/app-build-suite/pull/234), but example was not updated.
So I updated the example.
> Update team annotation to set a default value in example

- .github/CODEOWNERS
@piontec This CODEOWNERS file has an error. If you think it can be removed, please approve. Otherwise please let me know what should be in it.
> Delete CODEOWNERS file
